target-version = "py312"
exclude = [
    ".bzr",
    ".direnv",
    ".eggs",
    ".git",
    ".git-rewrite",
    ".hg",
    ".ipynb_checkpoints",
    ".mypy_cache",
    ".nox",
    ".pants.d",
    ".pyenv",
    ".pytest_cache",
    ".pytype",
    ".ruff_cache",
    ".svn",
    ".tox",
    ".venv",
    ".vscode",
    "__pypackages__",
    "_build",
    "buck-out",
    "build",
    "dist",
    "node_modules",
    "site-packages",
    "venv",
    "out",
    "typings",
    ".pyre",
]
line-length = 88
indent-width = 4

[lint]
select = ["ALL"]
external = ["WPS", "C", "W"]
ignore = ["RUF100", "COM812", "ISC001", "FIX002"]
fixable = ["ALL"]
unfixable = []
dummy-variable-rgx = "^(_+|(_+[a-zA-Z0-9_]*[a-zA-Z0-9]+?))$"

[lint.per-file-ignores]
"tests/**/test_*.py" = [
    "S101",  # Checks for uses of the assert keyword
    "DJ008", # Checks that a __str__ method is defined in Django models
    "D100",  # Missing docstring in public module
]

[lint.pydocstyle]
convention = "google"

[lint.pycodestyle]
ignore-overlong-task-comments = true

[format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"
