# Generated by Django 5.2 on 2025-05-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForeignModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="M2MOptional",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("field", models.ManyToManyField(blank=True, to="tests.foreignmodel")),
            ],
        ),
        migrations.CreateModel(
            name="M2MRequired",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("field", models.ManyToManyField(to="tests.foreignmodel")),
            ],
        ),
    ]
