name: CI/CD pipeline

on:
  push:
    branches:
      - "*"

jobs:
  tests:
    uses: NextGenContributions/cicd-pipeline/.github/workflows/test.yml@main
    with:
      project_name: django2pydantic

  release:
    uses: NextGenContributions/cicd-pipeline/.github/workflows/release.yml@main
    with:
      release_branch: main
    needs: tests
    permissions:
      id-token: write
      contents: write

  publish-to-testpypi:
    uses: NextGenContributions/cicd-pipeline/.github/workflows/publish-pypi.yml@main
    with:
      project_name: django2pydantic
    if: ${{ needs.release.outputs.released == 'true' }}
    needs:
      - release
    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing
